name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      uses: actions/checkout@v2
      - name: build
      run: make build
      - name: status
      run: echo "This job's status is ${{ job.status }}."